# ~/.config/starship.toml

# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
# vicmd_symbol = "[<](bold green)"

[cmd_duration]
show_milliseconds = true

[directory]
read_only = " ro"

[hostname]
ssh_only = false
disabled = false

[username]
disabled = false
show_always = true

[time]
disabled = false

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = "git "

[git_metrics]
disabled = false

[c]
symbol = "C "
# the commands of the Tiny C Compiler
# commands = [["tcc", "-vv"]]

[dotnet]
format = "via [$symbol($version )(tfm $tfm )]($style)"
symbol = ".NET "

[golang]
symbol = "go "

[java]
symbol = "java "

[lua]
symbol = "lua "
detect_folders = [""]

[nodejs]
symbol = "nodejs "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[purescript]
symbol = "purs "

[rust]
symbol = "rs "
