language en_US
set number
set showmatch
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set smarttab
syntax on
set mouse=a
set wildmode=longest,list
set cursorline
set termguicolors
colorscheme atlas
